name: Test Minitrice

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Rendre le script exécutable
      run: chmod +x minitrice.py
      
    - name: Créer le dossier results et exécuter les test
      run: |
        mkdir -p results
        cat test/00-addition.txt | ./minitrice.py > results/00-addition-result.txt
        exit_code=$?
        echo "Résultat de l'execution: $exit_code" >> results/00-addition-result.txt

    - name: Sauvegarder les fichiers
      uses: actions/upload-artifact@v4
      with:
        name: resultats-minitrice
        path: results/

    - name: Commit et push des résultats
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add results/
        git commit -m "test(test_minitrice.yml) ajout des résultat de test"
        git push origin HEAD:main  # Remplacez 'main' par votre branche cible si nécessaire
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Utilise le token fourni par GitHub Actions
